# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Prompt template for domain-specific customization of the video reasoning annotation pipeline.

This file mirrors the structure of prompts.py but uses [PLACEHOLDER] markers
where you should insert domain-specific text. The built-in prompts.py provides
a working general-purpose default; this template shows how to adapt them.

INSTRUCTIONS:
1. Copy this file and rename it (e.g., prompts_traffic.py).
2. Replace all [PLACEHOLDER] markers with domain-specific text.
3. Set ``prompts_module`` in your video_reasoning_annotation YAML config to the dotted import
   path of your customized module (e.g., "my_package.prompts_traffic").
4. Your module must expose a ``PROMPT_TEMPLATES`` dict with the same keys.

The general-purpose prompts in prompts.py are used when prompts_module is empty.
"""

PROMPT_TEMPLATES = {
    # =========================================================================
    # VIDEO FILTERING
    # =========================================================================
    "video_filtering": (
        "Determine if this video belongs to [DOMAIN].\n\n"
        "A [DOMAIN] video should have:\n"
        "- [POSITIVE_CRITERION_1]\n"
        "- [POSITIVE_CRITERION_2]\n"
        "- [POSITIVE_CRITERION_3]\n\n"
        "Negative examples (NOT [DOMAIN]):\n"
        "- [EXCLUSION_1]\n"
        "- [EXCLUSION_2]\n\n"
        'Answer with ONLY "Yes" or "No".'
    ),
    # =========================================================================
    # ANOMALY CLASSIFICATION
    # =========================================================================
    "video_anomaly_classification": (
        "You are an expert [DOMAIN] analyst. Watch this video and classify "
        "whether it contains an anomalous event or only normal activity.\n\n"
        "An anomaly in [DOMAIN] is [ANOMALY_DEFINITION].\n\n"
        "Examples of anomalies:\n"
        "- [ANOMALY_EXAMPLE_1]\n"
        "- [ANOMALY_EXAMPLE_2]\n"
        "- [ANOMALY_EXAMPLE_3]\n\n"
        "Examples of normal activity:\n"
        "- [NORMAL_EXAMPLE_1]\n"
        "- [NORMAL_EXAMPLE_2]\n"
        "- [NORMAL_EXAMPLE_3]\n\n"
        "[EDGE_CASE_GUIDANCE]\n\n"
        "First, briefly describe what you observe in the video (2-3 "
        "sentences). Then explain your reasoning for the classification "
        "(2-3 sentences). Finally, on the LAST line, write your "
        'classification as exactly one word: "Anomaly" or "Normal".'
    ),
    # =========================================================================
    # ANOMALY CAPTIONING
    # =========================================================================
    "anomaly_global_caption": (
        "You are an expert [DOMAIN] analyst. Watch the video carefully.\n\n"
        "Describe this video in detail, addressing the following points in a "
        "cohesive narrative:\n"
        "- **[KEY_ASPECT_1]**: [DESCRIPTION_OF_WHAT_TO_OBSERVE]\n"
        "- **[KEY_ASPECT_2]**: [DESCRIPTION_OF_WHAT_TO_OBSERVE]\n"
        "- **[KEY_ASPECT_3 — The Anomaly / Incident]**: Describe the unusual "
        "or anomalous event in detail. What exactly happened? Identify all "
        "actors involved and describe their specific actions leading up to, "
        "during, and immediately after the event.\n"
        "- **[KEY_ASPECT_4 — Cause and Consequence]**: What was the apparent "
        "root cause? What were the immediate consequences?\n\n"
        "Provide a holistic summary that captures the complete story and "
        "context. Pay close attention to temporal and spatial details. "
        "Do not hallucinate or make up information."
    ),
    "anomaly_dense_caption": (
        "You are an expert [DOMAIN] analyst. Provide a dense, event-level "
        "video caption with precise timestamps for a video containing an "
        "anomalous event.\n\n"
        "Structure your response as a list of events. For each event, "
        "provide the start and end timestamp in the format "
        "<HH:MM:SS><HH:MM:SS> followed by a detailed description.\n\n"
        "Focus particularly on:\n"
        "1. **Precise Timing**: Accurately capture the start and end of "
        "each distinct action or state change.\n"
        "2. **Anomalous Actions**: Describe in detail the actions involved "
        "in the anomaly — what happened, how, and the sequence of events.\n"
        "3. **[DOMAIN_ACTOR_DETAILS]**: [WHAT_TO_TRACK_FOR_ACTORS]\n"
        "4. **[DOMAIN_SPATIAL_CONTEXT]**: [WHAT_SPATIAL_DETAILS_TO_NOTE]\n"
        "5. **[DOMAIN_ENVIRONMENTAL_FACTORS]**: [WHAT_CONDITIONS_TO_MENTION]\n\n"
        "Format each line as:\n"
        "<Start_Timestamp><End_Timestamp> Description of the event.\n\n"
        "Example:\n"
        "[DOMAIN_SPECIFIC_EXAMPLE_LINE_1]\n"
        "[DOMAIN_SPECIFIC_EXAMPLE_LINE_2]\n"
        "[DOMAIN_SPECIFIC_EXAMPLE_LINE_3]\n"
        "[DOMAIN_SPECIFIC_EXAMPLE_LINE_4]"
    ),
    "anomaly_chunk_caption": (
        "You are an expert [DOMAIN] analyst. You are viewing a strict "
        "{chunk_duration}-second window of a video that contains an anomaly "
        "somewhere in the full video.\n"
        "Your job is NOT to tell the whole story, but to capture the "
        "**micro-dynamics** and **state changes** within this specific "
        "timeframe.\n\n"
        "Note: This specific chunk may or may not contain the anomaly — "
        "it covers only a fixed time window. Describe only what you observe "
        "in this clip; do not assume or fabricate anomalous content if it "
        "is not visible.\n\n"
        "Please describe the events in this {chunk_duration}-second window, "
        "focusing on:\n\n"
        "1. **[DOMAIN_DYNAMICS]**:\n"
        "   - [WHAT_ACTIONS_TO_DESCRIBE]\n"
        "   - [WHAT_DETAILS_TO_CAPTURE]\n\n"
        "2. **[DOMAIN_CONTEXT]**:\n"
        "   - [WHAT_ENVIRONMENTAL_FACTORS_TO_NOTE]\n"
        "   - [WHAT_CONDITIONS_TO_MENTION]\n\n"
        "3. **Anomaly or Interaction Details**:\n"
        "   - If an anomaly occurs or is imminent in this chunk, describe "
        "the sequence of interactions and specific anomalous actions.\n"
        "   - If the aftermath is visible, describe the post-event state.\n"
        "   - If no anomaly is visible, describe the normal dynamics.\n\n"
        "Do not speculate on what happened before or after this clip. "
        "Report only what is visually confirmed in these "
        "{chunk_duration} seconds. Be precise and objective."
    ),
    # =========================================================================
    # NORMAL CAPTIONING
    # =========================================================================
    "normal_global_caption": (
        "You are an expert [DOMAIN] analyst. Watch the video carefully.\n\n"
        "Describe this video in detail, addressing the following points in a "
        "cohesive narrative:\n"
        "- **[KEY_ASPECT_1]**: [DESCRIPTION_FOR_NORMAL_SCENARIOS]\n"
        "- **[KEY_ASPECT_2]**: [DESCRIPTION_FOR_NORMAL_SCENARIOS]\n"
        "- **[KEY_ASPECT_3 — Activities and Behaviors]**: What is happening? "
        "Describe the main activities, movements, interactions, and behaviors.\n"
        "- **[KEY_ASPECT_4 — Overall Context]**: Summarize the situation, "
        "the general purpose or routine being observed.\n\n"
        "Provide a holistic summary that captures the complete picture. "
        "Pay close attention to temporal and spatial details. "
        "Do not hallucinate or make up information."
    ),
    "normal_dense_caption": (
        "You are an expert [DOMAIN] analyst. Provide a dense, event-level "
        "video caption with precise timestamps for this video showing normal "
        "activity.\n\n"
        "Structure your response as a list of events. For each event, "
        "provide the start and end timestamp in the format "
        "<HH:MM:SS><HH:MM:SS> followed by a detailed description.\n\n"
        "Focus particularly on:\n"
        "1. **Precise Timing**: Accurately capture the start and end of "
        "each distinct action, movement, or state change.\n"
        "2. **[DOMAIN_BEHAVIORS]**: [WHAT_NORMAL_ACTIVITIES_TO_DESCRIBE]\n"
        "3. **[DOMAIN_ACTOR_DETAILS]**: [WHAT_TO_TRACK_FOR_ACTORS]\n"
        "4. **[DOMAIN_SPATIAL_CONTEXT]**: [WHAT_SPATIAL_DETAILS_TO_NOTE]\n\n"
        "Format each line as:\n"
        "<Start_Timestamp><End_Timestamp> Description of the event.\n\n"
        "Example:\n"
        "[DOMAIN_SPECIFIC_NORMAL_EXAMPLE_LINE_1]\n"
        "[DOMAIN_SPECIFIC_NORMAL_EXAMPLE_LINE_2]\n"
        "[DOMAIN_SPECIFIC_NORMAL_EXAMPLE_LINE_3]\n"
        "[DOMAIN_SPECIFIC_NORMAL_EXAMPLE_LINE_4]"
    ),
    "normal_chunk_caption": (
        "You are an expert [DOMAIN] analyst. You are viewing a strict "
        "{chunk_duration}-second window of a video showing normal activity "
        "with no anomalous events.\n"
        "Your job is NOT to tell the whole story, but to capture the "
        "**micro-dynamics** and **state changes** within this specific "
        "timeframe.\n\n"
        "Please describe the events in this {chunk_duration}-second window, "
        "focusing on:\n\n"
        "1. **[DOMAIN_DYNAMICS]**:\n"
        "   - [WHAT_ACTIONS_TO_DESCRIBE]\n"
        "   - [WHAT_DETAILS_TO_CAPTURE]\n\n"
        "2. **[DOMAIN_CONTEXT]**:\n"
        "   - [WHAT_ENVIRONMENTAL_FACTORS_TO_NOTE]\n"
        "   - [WHAT_CONDITIONS_TO_MENTION]\n\n"
        "3. **[DOMAIN_INTERACTIONS]**:\n"
        "   - [WHAT_INTERACTIONS_TO_NOTE]\n"
        "   - [WHAT_PATTERNS_TO_DESCRIBE]\n\n"
        "Do not speculate on what happened before or after this clip. "
        "Report only what is visually confirmed in these "
        "{chunk_duration} seconds. Be precise and objective."
    ),
    # =========================================================================
    # HIGHLIGHT CHUNK (ANOMALY ONLY)
    # =========================================================================
    "highlight_timestamp_extraction": (
        "You are an expert [DOMAIN] analyst. Given the captions below for a "
        "video containing an anomaly, identify the EXACT timestamp (in "
        "seconds) when the primary anomaly occurs — the critical moment "
        "of the incident itself, not the lead-up behavior before it and "
        "not the aftermath.\n\n"
        "Use the chunk captions to cross-reference and narrow down the "
        "precise moment, since they provide detailed observations for "
        "specific time windows.\n\n"
        "Respond with ONLY a single number representing the timestamp in "
        'seconds (e.g., "20" or "12.5"). Nothing else.\n\n'
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}\n\n"
        "[Chunk Captions]\n{chunk_captions_str}"
    ),
    "highlight_chunk_caption": (
        "You are an expert [DOMAIN] analyst. You are viewing a critical "
        "{duration}-second highlight clip extracted from a longer video, "
        "centered on the moment an anomaly occurs.\n\n"
        "This clip spans from {start_time}s to {end_time}s of the "
        "original video. The anomaly is estimated to occur at "
        "approximately {anomaly_time}s.\n\n"
        "Provide an extremely detailed description of what happens in "
        "this clip, with special attention to:\n\n"
        "1. **Pre-Event State** (first 1–3 seconds):\n"
        "   - Exact positions and states of all key actors/objects\n"
        "   - Directions of movement, speed (fast/slow/stopped)\n"
        "   - [DOMAIN_SPECIFIC_PRE_EVENT_DETAILS]\n\n"
        "2. **The Critical Moment** (the anomaly itself):\n"
        "   - Exactly what happens — the specific [DOMAIN_EVENT_TYPE]\n"
        "   - Which actors are involved and from what angle/direction\n"
        "   - [DOMAIN_SPECIFIC_CRITICAL_DETAILS]\n\n"
        "3. **Immediate Aftermath** (last 1–3 seconds):\n"
        "   - Where actors/objects end up after the event\n"
        "   - Whether any secondary events occur\n"
        "   - [DOMAIN_SPECIFIC_AFTERMATH_DETAILS]\n\n"
        "Be extremely precise about identifying actors and who does what. "
        "Do NOT hallucinate or assume actions you cannot confirm from the video."
    ),
    # =========================================================================
    # DESCRIPTION GENERATION (TEXT-TO-TEXT)
    # =========================================================================
    "anomaly_description": (
        "You are an expert [DOMAIN] analyst. You are provided with captions "
        "for a video containing an anomaly:\n"
        "1. Global Caption: General description of the scene and events.\n"
        "2. Event-level Dense Caption: Detailed event sequence with "
        "timestamps.\n"
        "3. Chunk Captions: Detailed captions for small time windows.\n\n"
        "Task: Generate a detailed, organized, and cohesive description "
        "of the video with exactly these 3 parts:\n"
        "1. Holistic Scene Description — Describe the setting, layout, "
        "conditions, and general context of the scene.\n"
        "2. Temporal and Spatial Localization of Anomaly Events — List "
        "each key event in chronological order using this exact format "
        "(one event per line, timestamp in MM:SS):\n"
        "<start timestamp MM:SS><end timestamp MM:SS> [where in the scene] "
        "what happened\n"
        "3. Description of the Anomaly — Covering:\n"
        "   - Category of anomaly\n"
        "   - Detailed description of the event\n"
        "   - Time and duration\n"
        "   - Spatial location within the scene\n"
        "   - Reason for abnormality (root cause)\n"
        "   - Consequences\n\n"
        "Instructions for using input data:\n"
        "- Use the [Global Caption] for general scene/event descriptions.\n"
        "- Use the [Dense Caption] to identify timestamps and temporal "
        "sequence of events.\n"
        "- Use [Chunk Captions] for detailed micro-level observations "
        "prior to, during, and after the anomaly.\n"
        "- If a [Highlight Chunk Caption] is provided, treat it as the "
        "most reliable source for the anomaly moment. Prioritize it over "
        "chunk captions for Parts 2 and 3. If no highlight is provided, "
        "rely on the other captions.\n"
        "- Resolve conflicts by using information most captions agree on.\n\n"
        "Output formatting rules (strictly enforced):\n"
        "- NEVER reference the source of information. Do not write "
        'phrases like "the global caption states". Write as if you are '
        "directly observing the video.\n"
        "- Refer to actors by their visual attributes, not by ID numbers.\n\n"
        "Input Captions:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "{dense_section}\n\n"
        "[Chunk Captions]\n{chunk_captions_str}\n\n"
        "{highlight_section}"
    ),
    "normal_description": (
        "You are an expert [DOMAIN] analyst. You are provided with captions "
        "for a video showing normal activity.\n\n"
        "Task: Generate a detailed, organized, and cohesive description "
        "of the video with exactly these 3 parts:\n"
        "1. Holistic Scene Description — Describe the setting, layout, "
        "conditions, and general context.\n"
        "2. Temporal and Spatial Localization of Key Events — List each "
        "notable event in chronological order using this exact format "
        "(one event per line, timestamp in MM:SS):\n"
        "<start timestamp MM:SS><end timestamp MM:SS> [where in the scene] "
        "what happened\n"
        "3. Event Description — An activity summary. Structure this "
        'section as bullet points, each in "Key: value" format. Cover '
        "the overall activities, key behaviors, notable interactions, and "
        "patterns observed.\n\n"
        "Instructions:\n"
        "- Use the [Global Caption] for general scene and activity "
        "descriptions.\n"
        "- Use the [Dense Caption] for the timestamped sequence of events.\n"
        "- Use [Chunk Captions] for detailed micro-level observations.\n"
        "- Resolve conflicts by using what most sources agree on.\n"
        "- Do not fabricate events not present in the captions.\n"
        "- NEVER reference the source of information. Write as if you "
        "are directly observing the video.\n\n"
        "Input Captions:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "{dense_section}\n\n"
        "[Chunk Captions]\n{chunk_captions_str}"
    ),
    # =========================================================================
    # QA GENERATION — MCQ
    # =========================================================================
    "anomaly_mcq": (
        "You are an expert [DOMAIN] analyst. You are provided with captions "
        "and a description for a video containing an anomaly.\n\n"
        "Task:\n"
        "1. Design a multiple-choice question about the anomaly that "
        "requires perception and reasoning to answer.\n"
        "2. The question should focus on one of: the root cause of the "
        "anomaly, its direct consequence, the sequence of events, who or "
        "what was involved, or the type/category of the incident.\n"
        "3. The question must be unambiguous: phrased so there is exactly "
        "one correct interpretation and one correct answer based on the "
        "video.\n"
        "4. Each wrong option must be clearly incorrect based on the "
        "video, not merely less likely. All options should be specific "
        "and parallel in structure.\n"
        "5. Provide step-by-step reasoning to derive the answer. The "
        "reasoning should proceed from observations through causal "
        "inference to the conclusion.\n"
        "6. Treat all captions as a representation of the video itself. "
        'Don\'t mention "Global Caption", "Dense Caption", or '
        '"Chunk Captions" — only mention the video.\n'
        "7. Ground your Question, Answer, and Reasoning on the provided "
        "data. Don't hallucinate or make up information.\n\n"
        "Here is an example of the desired content style and depth. "
        "(Note: this is for illustration only — your output must be "
        "based on the actual content of the video provided, not this "
        "example.)\n"
        "<example>\n"
        "[DOMAIN_MCQ_EXAMPLE_QUESTION]\n"
        "[DOMAIN_MCQ_EXAMPLE_OPTIONS]\n"
        "======\n"
        "[DOMAIN_MCQ_EXAMPLE_ANSWER]\n"
        "=====\n"
        "Reasoning:\n"
        "[DOMAIN_MCQ_EXAMPLE_REASONING]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Multiple-Choice Question: [Question]\n"
        "A. [Option A]\n"
        "B. [Option B]\n"
        "C. [Option C]\n"
        "D. [Option D]\n"
        "======\n"
        "Answer: [Answer] (should be a single letter choice)\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}\n\n"
        "[Chunk Captions]\n{chunk_captions_str}\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    "normal_mcq": (
        "You are an expert [DOMAIN] analyst. You are provided with captions "
        "for a video with a normal scenario.\n\n"
        "Task:\n"
        "1. Design a multiple-choice question that requires perception "
        "and preferably reasoning to answer.\n"
        "2. The question should focus on: identifying what is happening, "
        "who or what is involved, the sequence of events, spatial "
        "relationships, or environmental conditions.\n"
        "3. The question must be unambiguous with exactly one correct "
        "answer. Each wrong option must be clearly incorrect, not "
        "merely less likely. All options should be specific and parallel.\n"
        "4. Provide step-by-step reasoning to derive the answer.\n"
        "5. Treat all captions as a representation of the video itself. "
        'Don\'t mention "Global Caption" or "Dense Caption" — only '
        "mention the video.\n"
        "6. Ground your output on the provided data. Don't hallucinate.\n\n"
        "Here is an example of the desired content style and depth. "
        "(Note: this is for illustration only.)\n"
        "<example>\n"
        "[DOMAIN_NORMAL_MCQ_EXAMPLE_QUESTION]\n"
        "[DOMAIN_NORMAL_MCQ_EXAMPLE_OPTIONS]\n"
        "======\n"
        "[DOMAIN_NORMAL_MCQ_EXAMPLE_ANSWER]\n"
        "=====\n"
        "Reasoning:\n"
        "[DOMAIN_NORMAL_MCQ_EXAMPLE_REASONING]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Multiple-Choice Question: [Question]\n"
        "A. [Option A]\n"
        "B. [Option B]\n"
        "C. [Option C]\n"
        "D. [Option D]\n"
        "======\n"
        "Answer: [Answer] (should be a single letter choice)\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}"
    ),
    # =========================================================================
    # QA GENERATION — BINARY
    # =========================================================================
    "anomaly_bcq": (
        "You are an expert [DOMAIN] analyst. You are provided with captions "
        "and a description for a video containing an anomaly.\n\n"
        "Task:\n"
        '1. Design two binary questions, one with answer "Yes." and '
        'one with answer "No.". Don\'t make the questions too '
        "complicated. They should be straightforward but still require "
        "observing and reasoning about the video carefully.\n"
        "2. For each question, provide a step-by-step reasoning of how "
        "to derive the answer based on the video. Start from observation "
        "and description of the video and the anomalous event, then "
        "reason/analyze the question.\n"
        "3. Treat the description as a representation of the video "
        "itself. Generate the Question, Answer, and Reasoning as if you "
        "are looking at the video directly. Don't mention the description "
        "in the Question, Answer, or Reasoning. Only mention the video.\n"
        "4. Ground your output on the provided data. Don't hallucinate.\n\n"
        "Here is an example of the desired content style and depth. "
        "(Note: this is for illustration only — your output must be "
        "based on the actual content of the video provided, not this "
        "example.)\n"
        "<example>\n"
        "[DOMAIN_BCQ_EXAMPLE_QUESTION]\n"
        "======\n"
        "[DOMAIN_BCQ_EXAMPLE_ANSWER]\n"
        "=====\n"
        "Reasoning:\n"
        "[DOMAIN_BCQ_EXAMPLE_REASONING]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "1. Question: [Question]\n"
        "======\n"
        "Answer: Yes. [Additional explanation in one sentence]\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n"
        "=====\n"
        "2. Question: [Question]\n"
        "======\n"
        "Answer: No. [Additional explanation in one sentence]\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}\n\n"
        "[Chunk Captions]\n{chunk_captions_str}\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    "normal_bcq": (
        "You are an expert [DOMAIN] analyst. You are provided with captions "
        "for a video with a normal scenario.\n\n"
        "Task:\n"
        '1. Design two binary questions, one with answer "Yes." and '
        'one with answer "No.". Don\'t make the questions too '
        "complicated. They should be straightforward but still require "
        "observing and reasoning about the video carefully. Focus on "
        "observable events, actor behaviors, spatial relationships, "
        "or environmental conditions.\n"
        "2. For each question, provide a step-by-step reasoning of "
        "how to derive the answer based on the video. Start from "
        "observation and description, then reason/analyze.\n"
        "3. Treat the description as a representation of the video "
        "itself. Don't mention the description. Only mention the video.\n"
        "4. Ground your output on the provided data. Don't hallucinate.\n\n"
        "Here is an example of the desired content style and depth. "
        "(Note: this is for illustration only.)\n"
        "<example>\n"
        "[DOMAIN_NORMAL_BCQ_EXAMPLE_QUESTION]\n"
        "======\n"
        "[DOMAIN_NORMAL_BCQ_EXAMPLE_ANSWER]\n"
        "=====\n"
        "Reasoning:\n"
        "[DOMAIN_NORMAL_BCQ_EXAMPLE_REASONING]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "1. Question: [Question]\n"
        "======\n"
        "Answer: Yes. [Additional explanation in one sentence]\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n"
        "=====\n"
        "2. Question: [Question]\n"
        "======\n"
        "Answer: No. [Additional explanation in one sentence]\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}"
    ),
    # =========================================================================
    # QA GENERATION — OPEN-ENDED
    # =========================================================================
    "anomaly_open_qa": (
        "You are an expert [DOMAIN] analyst. You are provided with captions "
        "and a description for a video containing an anomaly.\n\n"
        "Task:\n"
        "1. Design an open-ended question about the anomaly that "
        "requires perception and reasoning to answer.\n"
        "2. The question should ask about the root cause, consequence, "
        "sequence of events, or what should have been done differently.\n"
        "3. Provide step-by-step reasoning to derive the answer. The "
        "reasoning should proceed from observations through causal "
        "inference to the conclusion.\n"
        "4. Treat all captions as a representation of the video itself. "
        'Don\'t mention "Global Caption", "Dense Caption", or '
        '"Chunk Captions" — only mention the video.\n'
        "5. Ground your output on the provided data. Don't hallucinate.\n\n"
        "Here is an example of the desired content style and depth. "
        "(Note: this is for illustration only — your output must be "
        "based on the actual content of the video provided, not this "
        "example.)\n"
        "<example>\n"
        "[DOMAIN_OPEN_QA_EXAMPLE_QUESTION]\n"
        "======\n"
        "[DOMAIN_OPEN_QA_EXAMPLE_ANSWER]\n"
        "=====\n"
        "Reasoning:\n"
        "[DOMAIN_OPEN_QA_EXAMPLE_REASONING]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Open-ended Question: [Question]\n"
        "======\n"
        "Answer: [Answer] (open-ended, should be a paragraph)\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}\n\n"
        "[Chunk Captions]\n{chunk_captions_str}\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    "normal_open_qa": (
        "You are an expert [DOMAIN] analyst. You are provided with captions "
        "for a video with a normal scenario.\n\n"
        "Task:\n"
        "1. Design an open-ended question that requires perception and "
        "preferably reasoning to answer.\n"
        "2. The question should ask about what is happening, why events "
        "unfold as they do, how actors interact, or what the observable "
        "patterns reveal about the scene.\n"
        "3. Provide step-by-step reasoning to derive the answer.\n"
        "4. Treat all captions as a representation of the video itself. "
        'Don\'t mention "Global Caption" or "Dense Caption" — only '
        "mention the video.\n"
        "5. Ground your output on the provided data. Don't hallucinate.\n\n"
        "Here is an example of the desired content style and depth. "
        "(Note: this is for illustration only.)\n"
        "<example>\n"
        "[DOMAIN_NORMAL_OPEN_QA_EXAMPLE_QUESTION]\n"
        "======\n"
        "[DOMAIN_NORMAL_OPEN_QA_EXAMPLE_ANSWER]\n"
        "=====\n"
        "Reasoning:\n"
        "[DOMAIN_NORMAL_OPEN_QA_EXAMPLE_REASONING]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Open-ended Question: [Question]\n"
        "======\n"
        "Answer: [Answer] (open-ended, should be a paragraph)\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}"
    ),
    # =========================================================================
    # QA GENERATION — SCENE DESCRIPTION (mode-independent)
    # =========================================================================
    "scene_description": (
        "You are an expert [DOMAIN] analyst. You are provided with a "
        "detailed description for a [DOMAIN] video. Your task is to "
        "produce a **scene description caption** that captures the "
        "static, spatial layout of the scene — not the events that "
        "unfold over time.\n\n"
        "Task:\n"
        "1. Write a **question** — a natural-language question whose "
        "answer is the scene description caption. The question should "
        "ask about the physical setting, layout, or environmental "
        "context of the video.\n"
        "2. Write an **answer** — a concise yet thorough scene "
        "description covering:\n"
        "   - The camera perspective.\n"
        "   - Weather, lighting, and approximate time of day.\n"
        "   - [DOMAIN_LAYOUT_DETAILS]: [WHAT_TO_DESCRIBE_ABOUT_LAYOUT]\n"
        "   - [DOMAIN_INFRASTRUCTURE]: [WHAT_FIXED_ELEMENTS_TO_NOTE]\n"
        "   - Stationary objects and environment.\n"
        "   - People/objects present and their attributes.\n"
        "   Do NOT describe events, movements, or actions.\n"
        "3. Write a **reasoning** — a coherent paragraph explaining "
        "how observations lead to each element of the answer. Do not "
        "use bullet points or numbered lists.\n"
        "4. Treat the description as a representation of the video "
        "itself. Do not mention the description in the output.\n"
        "5. Ground your output on the provided data. Do not "
        "hallucinate.\n\n"
        "Here are examples of the desired answer style and depth. "
        "(Note: for illustration only.)\n"
        "<example>\n"
        "[DOMAIN_SCENE_DESCRIPTION_EXAMPLE]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Question about the scene layout]\n"
        "=====\n"
        "Answer: [Scene description caption]\n"
        "=====\n"
        "Reasoning: [Coherent paragraph]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    # =========================================================================
    # QA GENERATION — EVENT SUMMARY (mode-independent)
    # =========================================================================
    "event_summary": (
        "You are an expert [DOMAIN] analyst. You are provided with a "
        "detailed description for a [DOMAIN] video. Your task is to "
        "produce an **event summary caption** that describes the key "
        "events and actions — not the static scene layout.\n\n"
        "Task:\n"
        "1. Write a **question** — a natural-language question whose "
        "answer is the event summary caption.\n"
        "2. Write an **answer** — a concise yet thorough event summary "
        "covering:\n"
        "   - A brief, high-level summary of all key events.\n"
        "   - [DOMAIN_NORMAL_EVENTS]: [WHAT_TO_DESCRIBE_FOR_NORMAL]\n"
        "   - [DOMAIN_ANOMALY_EVENTS]: [WHAT_TO_DESCRIBE_FOR_ANOMALY]\n"
        "   - **Root cause**: For any anomaly, explicitly state the "
        "root cause.\n"
        "   - Use timestamps (MM:SS) and spatial references where "
        "possible.\n"
        "3. Write a **reasoning** — a coherent paragraph tracing the "
        "sequence of events. Do not use bullet points or numbered "
        "lists.\n"
        "4. Treat the description as a representation of the video "
        "itself. Do not mention the description in the output.\n"
        "5. Ground your output on the provided data. Do not "
        "hallucinate.\n\n"
        "Here are examples of the desired answer style and depth. "
        "(Note: for illustration only.)\n"
        "<example>\n"
        "[DOMAIN_EVENT_SUMMARY_EXAMPLE]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Question about the events]\n"
        "=====\n"
        "Answer: [Event summary caption]\n"
        "=====\n"
        "Reasoning: [Coherent paragraph]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    # =========================================================================
    # QA GENERATION — TEMPORAL EVENT DESCRIPTION
    # =========================================================================
    "anomaly_temporal_event_desc": (
        "You are an expert [DOMAIN] analyst. You are provided with a "
        "detailed description for a [DOMAIN] video containing an "
        "anomaly.\n\n"
        "Task:\n"
        "1. Identify a single anomalous event and select [t1, t2] as "
        "the tight temporal window covering just that one event.\n"
        "2. Generate a question asking what happened between [t1] and "
        "[t2]. The question must contain ONLY the timestamps and a "
        "neutral phrasing.\n"
        "3. Provide an Answer as a single coherent paragraph.\n"
        "4. Provide a Reasoning trace in 2-3 coherent paragraphs.\n\n"
        "Constraints:\n"
        "- STRICT ADHERENCE TO TIMESTAMPS.\n"
        "- The Question must contain ONLY timestamps and neutral "
        "phrasing.\n"
        "- Answer and Reasoning must be coherent paragraphs, no bullet "
        "points.\n"
        "- Treat the description as a representation of the video.\n\n"
        "Here is an example of the desired output:\n"
        "<example>\n"
        "[DOMAIN_TEMPORAL_EVENT_DESC_ANOMALY_EXAMPLE]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Neutral question with only timestamps]\n"
        "======\n"
        "Answer: [Single paragraph]\n"
        "=====\n"
        "Reasoning: [2-3 coherent paragraphs]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    "normal_temporal_event_desc": (
        "You are an expert [DOMAIN] analyst. You are provided with a "
        "detailed description for a normal [DOMAIN] video.\n\n"
        "Task:\n"
        "1. Identify a single, self-contained event and select "
        "[t1, t2] as the tight temporal window covering just that "
        "one event.\n"
        "2. Generate a question asking what happened between [t1] and "
        "[t2]. The question must contain ONLY the timestamps and a "
        "neutral phrasing.\n"
        "3. Provide an Answer as a single coherent paragraph.\n"
        "4. Provide a Reasoning trace in 2-3 coherent paragraphs.\n\n"
        "Constraints:\n"
        "- STRICT ADHERENCE TO TIMESTAMPS.\n"
        "- The Question must contain ONLY timestamps and neutral "
        "phrasing.\n"
        "- Answer and Reasoning must be coherent paragraphs, no bullet "
        "points.\n"
        "- Treat the description as a representation of the video.\n\n"
        "Here is an example of the desired output:\n"
        "<example>\n"
        "[DOMAIN_TEMPORAL_EVENT_DESC_NORMAL_EXAMPLE]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Neutral question with only timestamps]\n"
        "======\n"
        "Answer: [Single paragraph]\n"
        "=====\n"
        "Reasoning: [2-3 coherent paragraphs]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    # =========================================================================
    # QA GENERATION — CAUSAL LINKAGE
    # =========================================================================
    "anomaly_causal_linkage": (
        "You are an expert [DOMAIN] analyst. You are provided with a "
        "detailed description for a [DOMAIN] video containing an "
        "anomaly.\n\n"
        "Task:\n"
        "1. Identify two distinct moments:\n"
        "   - [Timestamp A]: The triggering action or initial "
        "condition.\n"
        "   - [Timestamp B]: The subsequent outcome or consequence.\n"
        '2. Generate a "Blind" question using ONLY timestamps.\n'
        "3. Provide a Detailed Answer in a single paragraph.\n"
        "4. Provide a Reasoning Trace in 2-3 coherent paragraphs.\n\n"
        "Constraints:\n"
        '- The question MUST be "blind" (refer only to timestamps).\n'
        "- Answer: single narrative paragraph.\n"
        "- Reasoning: coherent paragraphs, no bullet points.\n"
        "- STRICT ADHERENCE TO TIMESTAMPS.\n"
        "- Treat the description as a representation of the video.\n\n"
        "Here is an example:\n"
        "<example>\n"
        "[DOMAIN_CAUSAL_LINKAGE_ANOMALY_EXAMPLE]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Question]\n"
        "======\n"
        "Answer: [Answer] (open-ended, should be a paragraph)\n"
        "=====\n"
        "Reasoning: [Coherent paragraphs]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    "normal_causal_linkage": (
        "You are an expert [DOMAIN] analyst. You are provided with a "
        "detailed description for a normal [DOMAIN] video.\n\n"
        "Task:\n"
        "1. Identify two distinct moments:\n"
        "   - [Timestamp A]: An initial action or condition.\n"
        "   - [Timestamp B]: The subsequent outcome.\n"
        '2. Generate a "Blind" question using ONLY timestamps.\n'
        "3. Provide a Detailed Answer in a single paragraph.\n"
        "4. Provide a Reasoning Trace in 2-3 coherent paragraphs.\n\n"
        "Constraints:\n"
        '- The question MUST be "blind" (refer only to timestamps).\n'
        "- Answer: single narrative paragraph.\n"
        "- Reasoning: coherent paragraphs, no bullet points.\n"
        "- STRICT ADHERENCE TO TIMESTAMPS.\n"
        "- Treat the description as a representation of the video.\n\n"
        "Here is an example:\n"
        "<example>\n"
        "[DOMAIN_CAUSAL_LINKAGE_NORMAL_EXAMPLE]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Question]\n"
        "======\n"
        "Answer: [Answer] (open-ended, should be a paragraph)\n"
        "=====\n"
        "Reasoning: [Coherent paragraphs]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    # =========================================================================
    # QA GENERATION — TEMPORAL LOCALIZATION
    # =========================================================================
    "anomaly_temporal_localization": (
        "You are an expert [DOMAIN] analyst specializing in temporal "
        "localization. You are provided with a detailed description "
        "for a [DOMAIN] video containing an anomaly.\n\n"
        "Task:\n"
        "1. Identify a significant event or anomaly to localize.\n"
        '2. Generate a question: "When does [Event X] occur?"\n'
        "3. Provide the Answer with exact start and end timestamps.\n"
        "4. Provide a Reasoning paragraph: Baseline → Trigger → "
        "Resolution.\n\n"
        "Constraints:\n"
        "- STRICT ADHERENCE TO TIMESTAMPS.\n"
        "- Reasoning: coherent paragraph, no bullet points.\n"
        "- Treat the description as a representation of the video.\n\n"
        "Here is an example:\n"
        "<example>\n"
        "[DOMAIN_TEMPORAL_LOCALIZATION_ANOMALY_EXAMPLE]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Question]\n"
        "======\n"
        "Answer: Start_Time: [MM:SS], End_Time: [MM:SS]\n"
        "=====\n"
        "Reasoning: [Coherent paragraph]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    "normal_temporal_localization": (
        "You are an expert [DOMAIN] analyst specializing in temporal "
        "localization. You are provided with a detailed description "
        "for a normal [DOMAIN] video.\n\n"
        "Task:\n"
        "1. Identify a significant event to localize.\n"
        '2. Generate a question: "When does [Event X] occur?"\n'
        "3. Provide the Answer with exact start and end timestamps.\n"
        "4. Provide a Reasoning paragraph: Before-State → "
        "Action/Transition → After-State.\n\n"
        "Constraints:\n"
        "- STRICT ADHERENCE TO TIMESTAMPS.\n"
        "- Reasoning: coherent paragraph, no bullet points.\n"
        "- Treat the description as a representation of the video.\n\n"
        "Here is an example:\n"
        "<example>\n"
        "[DOMAIN_TEMPORAL_LOCALIZATION_NORMAL_EXAMPLE]\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Question]\n"
        "======\n"
        "Answer: Start_Time: [MM:SS], End_Time: [MM:SS]\n"
        "=====\n"
        "Reasoning: [Coherent paragraph]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
}


def get_prompt(key, **kwargs):
    """Return the prompt template for the given key, formatted with kwargs."""
    template = PROMPT_TEMPLATES.get(key)
    if template is None:
        raise ValueError(f"No prompt template found for key: {key}")
    if kwargs:
        return template.format(**kwargs)
    return template
