# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Domain-agnostic prompt templates for the video reasoning annotation pipeline.

These prompts are designed to work with any general video content — traffic,
surveillance, workplace, outdoor, sports, etc. For domain-specific
customization, users can provide a custom prompts module via the
``prompts_module`` config field (see config_template.py for the structure).
"""

PROMPT_TEMPLATES = {
    # =========================================================================
    # VIDEO FILTERING
    # =========================================================================
    "video_filtering": (
        "Determine if this video contains meaningful visual content suitable "
        "for detailed analysis.\n\n"
        "A suitable video should have:\n"
        "- Clear visual content (not a blank screen, static image, or heavily corrupted)\n"
        "- Observable events, actions, or scenes involving people, vehicles, or objects\n"
        "- Sufficient length and continuity to describe (not just a single flash frame "
        "or a series of unrelated jump cuts)\n"
        "- A reasonably stable camera (fixed surveillance, static tripod, or smooth "
        "handheld — not extremely shaky or heavily distorted footage)\n\n"
        "Negative examples (NOT suitable):\n"
        "- Solid color screens, calibration patterns, or test signals\n"
        "- Footage that is >90%% occluded, black, or white\n"
        "- Videos with no discernible motion or activity throughout\n"
        "- Screen recordings of text, slideshows, or UI with no real-world content\n\n"
        'Answer with ONLY "Yes" or "No".'
    ),
    # =========================================================================
    # ANOMALY CLASSIFICATION
    # =========================================================================
    "video_anomaly_classification": (
        "You are an expert video analyst. Watch this video and classify "
        "whether it contains an anomalous event or only normal activity.\n\n"
        "An anomaly is any unexpected occurrence that deviates from the "
        "routine behavior expected in the scene — involving danger, rule "
        "violations, equipment failures, or sudden disruptions.\n\n"
        "Examples of anomalies:\n"
        "- Collisions, near-misses, or falls (e.g., vehicle collision at "
        "an intersection, a forklift striking shelving, a person tripping)\n"
        "- Rule violations (running red lights, jaywalking, entering "
        "restricted areas, bypassing safety equipment)\n"
        "- Equipment failures (spills, mechanical breakdowns, fires, "
        "structural collapses)\n"
        "- Behavioral disruptions (altercations, theft, crowd panic, "
        "erratic movements that break the scene's normal pattern)\n\n"
        "Examples of normal activity:\n"
        "- Traffic flow with vehicles obeying traffic signals and staying in lanes\n"
        "- Workers performing routine tasks following standard procedures\n"
        "- People walking, shopping, or interacting in expected ways\n\n"
        "Note: Near-misses count as anomalies even without contact. "
        "Minor violations count even without consequences. If ambiguous, "
        "default to Normal.\n\n"
        "First, briefly describe what you observe in the video (2-3 "
        "sentences). Then explain your reasoning for the classification "
        "(2-3 sentences). Finally, on the LAST line, write your "
        'classification as exactly one word: "Anomaly" or "Normal".'
    ),
    # =========================================================================
    # ANOMALY CAPTIONING
    # =========================================================================
    "anomaly_global_caption": (
        "You are an expert video analyst. Watch the video carefully.\n\n"
        "Describe this video in detail, addressing the following points in a "
        "cohesive narrative:\n"
        "- **Scene and Environment**: Describe the setting (indoor/outdoor, "
        "location type), physical layout, lighting conditions, weather (if "
        "applicable), and any notable environmental features (signage, "
        "infrastructure, equipment).\n"
        "- **Key Actors and Objects**: Identify the main people, vehicles, or "
        "objects in the scene. For each, note distinguishing attributes (color, "
        "type, size, clothing, position) and their initial state.\n"
        "- **The Anomaly / Incident**: Describe the unusual, unexpected, or "
        "anomalous event in detail. What exactly happened? Identify all "
        "actors involved and describe their specific actions leading up to, "
        "during, and immediately after the event.\n"
        "- **Cause and Consequence**: What was the apparent root cause of the "
        "anomaly? What were the immediate consequences (damage, disruption, "
        "reactions from others, changes to the scene)?\n\n"
        "Provide a holistic summary that captures the complete story and "
        "context. Pay close attention to temporal and spatial details \u2014 "
        "describe when things happen and where in the scene they occur. "
        "Do not hallucinate or make up information."
    ),
    "anomaly_dense_caption": (
        "You are an expert video analyst. Provide a dense, event-level "
        "video caption with precise timestamps for a video containing an "
        "anomalous event.\n\n"
        "Structure your response as a list of events. For each event, "
        "provide the start and end timestamp in the format "
        "<HH:MM:SS><HH:MM:SS> followed by a detailed description.\n\n"
        "Focus particularly on:\n"
        "1. **Precise Timing**: Accurately capture the start and end of "
        "each distinct action or state change.\n"
        "2. **Anomalous Actions**: Describe in detail the actions of people "
        "or objects involved in the anomaly \u2014 what they did, how, and the "
        "sequence of events leading to and through the incident.\n"
        "3. **Actor Details**: For every key actor, specify distinguishing "
        "attributes (color, type, size, clothing, position). Track their "
        "movements through the scene.\n"
        "4. **Spatial Context**: Note positions, directions of movement, "
        "spatial relationships, and locations within the frame (top, bottom, "
        "left, right, center).\n"
        "5. **Environmental Factors**: Mention conditions (lighting, weather, "
        "signals, signage) when relevant to the events.\n\n"
        "Format each line as:\n"
        "<Start_Timestamp><End_Timestamp> Description of the event.\n\n"
        "Example:\n"
        "<00:00:00><00:00:03> A wide intersection is visible from an overhead "
        "angle; vehicles are flowing normally from left to right.\n"
        "<00:00:03><00:00:05> A red sedan traveling from bottom to top "
        "approaches the intersection at moderate speed.\n"
        "<00:00:05><00:00:07> The red sedan enters the intersection; "
        "simultaneously, a white truck coming from left to right fails to "
        "stop, colliding with the sedan at the center of the intersection.\n"
        "<00:00:07><00:00:12> Both vehicles come to a stop; debris scatters "
        "across the roadway. Nearby vehicles brake and stop."
    ),
    "anomaly_chunk_caption": (
        "You are an expert video analyst. You are viewing a strict "
        "{chunk_duration}-second window of a video that contains an anomaly "
        "somewhere in the full video.\n"
        "Your job is NOT to tell the whole story, but to capture the "
        "**micro-dynamics** and **state changes** within this specific "
        "timeframe.\n\n"
        "Note: This specific chunk may or may not contain the anomaly \u2014 "
        "it covers only a fixed time window. Describe only what you observe "
        "in this clip; do not assume or fabricate anomalous content if it "
        "is not visible.\n\n"
        "Please describe the events in this {chunk_duration}-second window, "
        "focusing on:\n\n"
        "1. **Actions and Movements**:\n"
        "   - What specific actions, behaviors, or maneuvers are happening?\n"
        "   - How are people, vehicles, or objects moving or changing state?\n"
        "   - For each key actor, specify distinguishing attributes (color, "
        "type, clothing) and track their movement.\n\n"
        "2. **Environmental Context**:\n"
        "   - What are the conditions (lighting, weather, setting)?\n"
        "   - Are there notable spatial arrangements, signals, or signage?\n\n"
        "3. **Anomaly or Interaction Details**:\n"
        "   - If an anomaly occurs or is imminent in this chunk (collision, "
        "violation, unsafe action, equipment failure, suspicious behavior), "
        "describe the sequence of interactions and specific anomalous "
        "actions precisely.\n"
        "   - If the aftermath of an anomaly is visible (damage, stopped "
        "vehicles, reactions), describe the post-event state.\n"
        "   - If no anomaly is visible in this chunk, describe the normal "
        "dynamics observed.\n\n"
        "Do not speculate on what happened before or after this clip. "
        "Report only what is visually confirmed in these "
        "{chunk_duration} seconds. Be precise and objective."
    ),
    # =========================================================================
    # NORMAL CAPTIONING
    # =========================================================================
    "normal_global_caption": (
        "You are an expert video analyst. Watch the video carefully.\n\n"
        "Describe this video in detail, addressing the following points in a "
        "cohesive narrative:\n"
        "- **Scene and Environment**: Describe the setting (indoor/outdoor, "
        "location type), physical layout, lighting conditions, weather (if "
        "applicable), and any notable environmental features (signage, "
        "infrastructure, equipment).\n"
        "- **Key Actors and Objects**: Identify the main people, vehicles, "
        "or objects. For each, note distinguishing attributes (color, type, "
        "size, clothing, position).\n"
        "- **Activities and Behaviors**: What is happening in the video? "
        "Describe the main activities, movements, interactions, and "
        "behaviors observed. Note the pace, flow, and patterns of "
        "activity.\n"
        "- **Overall Context**: Summarize the situation \u2014 what kind of "
        "scene this is, the general purpose or routine being observed, "
        "and any notable temporal changes.\n\n"
        "Provide a holistic summary that captures the complete picture. "
        "Pay close attention to temporal and spatial details. "
        "Do not hallucinate or make up information."
    ),
    "normal_dense_caption": (
        "You are an expert video analyst. Provide a dense, event-level video "
        "caption with precise timestamps for this video showing normal "
        "activity.\n\n"
        "Structure your response as a list of events. For each event, "
        "provide the start and end timestamp in the format "
        "<HH:MM:SS><HH:MM:SS> followed by a detailed description.\n\n"
        "Focus particularly on:\n"
        "1. **Precise Timing**: Accurately capture the start and end of "
        "each distinct action, movement, or state change.\n"
        "2. **Activities and Behaviors**: Describe what people, vehicles, "
        "or objects are doing \u2014 specific actions, maneuvers, interactions, "
        "and task steps.\n"
        "3. **Actor Details**: For every key actor, specify distinguishing "
        "attributes (color, type, clothing, position). Track individuals "
        "through the scene.\n"
        "4. **Spatial Context**: Note positions, directions of movement, "
        "and spatial relationships within the frame.\n\n"
        "Format each line as:\n"
        "<Start_Timestamp><End_Timestamp> Description of the event.\n\n"
        "Example:\n"
        "<00:00:00><00:00:04> An open warehouse floor with shelving on both "
        "sides; a worker in a yellow vest is standing near a pallet.\n"
        "<00:00:04><00:00:08> The worker bends down, picks up a box from "
        "the pallet, and places it on a cart to the right.\n"
        "<00:00:08><00:00:12> A second worker enters from the left pushing "
        "an empty handcart; the first worker waves to acknowledge them.\n"
        "<00:00:12><00:00:16> Both workers begin loading boxes onto the "
        "handcart from separate pallets."
    ),
    "normal_chunk_caption": (
        "You are an expert video analyst. You are viewing a strict "
        "{chunk_duration}-second window of a video showing normal activity "
        "with no anomalous events.\n"
        "Your job is NOT to tell the whole story, but to capture the "
        "**micro-dynamics** and **state changes** within this specific "
        "timeframe.\n\n"
        "Please describe the events in this {chunk_duration}-second window, "
        "focusing on:\n\n"
        "1. **Actions and Movements**:\n"
        "   - What specific actions, behaviors, or maneuvers are happening?\n"
        "   - How are people, vehicles, or objects moving or changing state?\n"
        "   - For each key actor, specify distinguishing attributes and "
        "track their movement.\n\n"
        "2. **Environmental Context**:\n"
        "   - What are the conditions (lighting, weather, setting)?\n"
        "   - Are there notable spatial arrangements, signals, or signage?\n\n"
        "3. **Notable Interactions**:\n"
        "   - Describe any noteworthy interactions, task steps, or "
        "transitions between activities.\n"
        "   - Note any actors that stand out due to their behavior, speed, "
        "position, or actions.\n\n"
        "Do not speculate on what happened before or after this clip. "
        "Report only what is visually confirmed in these "
        "{chunk_duration} seconds. Be precise and objective."
    ),
    # =========================================================================
    # HIGHLIGHT CHUNK (ANOMALY ONLY)
    # =========================================================================
    "highlight_timestamp_extraction": (
        "You are an expert video analyst. Given the captions below for a "
        "video containing an anomaly, identify the EXACT timestamp (in "
        "seconds) when the primary anomaly occurs \u2014 the critical moment "
        "of the incident itself, not the lead-up behavior before it and "
        "not the aftermath.\n\n"
        "Use the chunk captions to cross-reference and narrow down the "
        "precise moment, since they provide detailed observations for "
        "specific time windows.\n\n"
        "Respond with ONLY a single number representing the timestamp in "
        'seconds (e.g., "20" or "12.5"). Nothing else.\n\n'
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}\n\n"
        "[Chunk Captions]\n{chunk_captions_str}"
    ),
    "highlight_chunk_caption": (
        "You are an expert video analyst. You are viewing a critical "
        "{duration}-second highlight clip extracted from a longer video, "
        "centered on the moment an anomaly occurs.\n\n"
        "This clip spans from {start_time}s to {end_time}s of the "
        "original video. The anomaly is estimated to occur at "
        "approximately {anomaly_time}s.\n\n"
        "Provide an extremely detailed description of what happens in "
        "this clip, with special attention to:\n\n"
        "1. **Pre-Event State** (first 1\u20133 seconds):\n"
        "   - Exact positions and states of all key actors/objects\n"
        "   - Directions of movement, speed (fast/slow/stopped)\n"
        "   - Environmental conditions (signals, lighting, spatial layout)\n"
        "   - Any last-second actions (braking, swerving, reaching, etc.)\n\n"
        "2. **The Critical Moment** (the anomaly itself):\n"
        "   - Exactly what happens \u2014 the specific action, collision, "
        "violation, failure, or dangerous event\n"
        "   - Which actors are involved and from what angle/direction\n"
        "   - The point of contact, moment of violation, or critical "
        "state change\n"
        "   - Immediate physical consequences (impact, debris, displacement, "
        "fall, etc.)\n\n"
        "3. **Immediate Aftermath** (last 1\u20133 seconds):\n"
        "   - Where actors/objects end up after the event\n"
        "   - Whether any secondary events occur\n"
        "   - Other actors' reactions (stopping, braking, looking, fleeing)\n\n"
        "Be extremely precise about identifying actors (color, type, "
        "direction) and who does what. Do NOT hallucinate or assume "
        "actions you cannot confirm from the video."
    ),
    # =========================================================================
    # DESCRIPTION GENERATION (TEXT-TO-TEXT)
    # =========================================================================
    "anomaly_description": (
        "You are an expert video analyst. You are provided with captions "
        "for a video containing an anomaly:\n"
        "1. Global Caption: General description of the scene and events.\n"
        "2. Event-level Dense Caption: Detailed event sequence with "
        "timestamps.\n"
        "3. Chunk Captions: Detailed captions for small time windows.\n\n"
        "Task: Generate a detailed, organized, and cohesive description "
        "of the video with exactly these 3 parts:\n"
        "1. Holistic Scene Description \u2014 Describe the setting, layout, "
        "conditions, and general context of the scene.\n"
        "2. Temporal and Spatial Localization of Anomaly Events \u2014 List "
        "each key event in chronological order using this exact format "
        "(one event per line, timestamp in MM:SS):\n"
        "<start timestamp MM:SS><end timestamp MM:SS> [where in the scene] "
        "what happened\n"
        "3. Description of the Anomaly \u2014 Covering:\n"
        "   - Category of anomaly\n"
        "   - Detailed description of the event\n"
        "   - Time and duration\n"
        "   - Spatial location within the scene\n"
        "   - Reason for abnormality (root cause, what went wrong, which "
        "actor was responsible)\n"
        "   - Consequences (damage, disruption, reactions, aftermath)\n\n"
        "Instructions for using input data:\n"
        "- Use the [Global Caption] for general scene/event descriptions.\n"
        "- Use the [Dense Caption] to identify timestamps and temporal "
        "sequence of events.\n"
        "- Use [Chunk Captions] for detailed micro-level observations "
        "prior to, during, and after the anomaly.\n"
        "- If a [Highlight Chunk Caption] is provided, treat it as the "
        "most reliable source for the anomaly moment. Prioritize it over "
        "chunk captions for Parts 2 and 3. If no highlight is provided, "
        "rely on the other captions.\n"
        "- Resolve conflicts by using information most captions agree on.\n\n"
        "Output formatting rules (strictly enforced):\n"
        "- NEVER reference the source of information. Do not write "
        'phrases like "the global caption states", "captions indicate", '
        "or any similar attribution. Write as if you are directly "
        "observing the video.\n"
        "- Refer to actors by their visual attributes (color, type, "
        "clothing, position), not by ID numbers or labels.\n\n"
        "Input Captions:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "{dense_section}\n\n"
        "[Chunk Captions]\n{chunk_captions_str}\n\n"
        "{highlight_section}"
    ),
    "normal_description": (
        "You are an expert video analyst. You are provided with captions "
        "for a video showing normal activity.\n\n"
        "Task: Generate a detailed, organized, and cohesive description "
        "of the video with exactly these 3 parts:\n"
        "1. Holistic Scene Description \u2014 Describe the setting, layout, "
        "conditions, and general context.\n"
        "2. Temporal and Spatial Localization of Key Events \u2014 List each "
        "notable event in chronological order using this exact format "
        "(one event per line, timestamp in MM:SS):\n"
        "<start timestamp MM:SS><end timestamp MM:SS> [where in the scene] "
        "what happened\n"
        "3. Event Description \u2014 An activity summary. Structure this "
        'section as bullet points, each in "Key: value" format (e.g. '
        '"- Activity type: ...", "- Key behaviors: ...", "- Notable '
        'interactions: ..."). Cover the overall activities being '
        "performed, key actor behaviors, notable interactions, and any "
        "patterns or transitions observed. Use whatever keys best capture "
        "the content.\n\n"
        "Instructions:\n"
        "- Use the [Global Caption] for general scene and activity "
        "descriptions.\n"
        "- Use the [Dense Caption] for the timestamped sequence of events "
        "and specific actions.\n"
        "- Use [Chunk Captions] for detailed micro-level observations of "
        "specific actors or moments. They cover short time windows and "
        "may lack full context \u2014 use them to supplement the Global and "
        "Dense Captions, not replace them.\n"
        "- Resolve conflicts by using what most sources agree on.\n"
        "- Do not fabricate events not present in the captions.\n"
        "- NEVER reference the source of information. Write as if you "
        "are directly observing the video.\n\n"
        "Input Captions:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "{dense_section}\n\n"
        "[Chunk Captions]\n{chunk_captions_str}"
    ),
    # =========================================================================
    # QA GENERATION \u2014 MCQ
    # =========================================================================
    "anomaly_mcq": (
        "You are an expert video analyst. You are provided with captions "
        "and a description for a video containing an anomaly.\n\n"
        "Task:\n"
        "1. Design a multiple-choice question about the anomaly that "
        "requires perception and reasoning to answer.\n"
        "2. The question should focus on one of: the root cause of the "
        "anomaly, its direct consequence, the sequence of events, who or "
        "what was involved, or the type/category of the incident.\n"
        "3. The question must be unambiguous: phrased so there is exactly "
        "one correct interpretation and one correct answer based on the "
        "video.\n"
        "4. Each wrong option must be clearly incorrect based on the "
        "video, not merely less likely. All options should be specific "
        "and parallel in structure.\n"
        "5. Provide step-by-step reasoning to derive the answer. The "
        "reasoning should proceed from observations (what is visible) "
        "through causal inference to the conclusion.\n"
        "6. Treat all captions as a representation of the video itself. "
        'Don\'t mention "Global Caption", "Dense Caption", or '
        '"Chunk Captions" \u2014 only mention the video.\n'
        "7. Ground your Question, Answer, and Reasoning on the provided "
        "data. Don't hallucinate or make up information.\n\n"
        "Here is an example of the desired content style and depth. "
        "(Note: this is for illustration only \u2014 your output must be "
        "based on the actual content of the video provided, not this "
        "example.)\n"
        "<example>\n"
        "Multiple-Choice Question: What is the primary cause of the "
        "collision at the intersection?\n"
        "A. A vehicle ran a red light while cross-traffic had the "
        "right of way\n"
        "B. A vehicle made an illegal U-turn in the intersection\n"
        "C. A pedestrian stepped into the roadway causing vehicles to "
        "swerve\n"
        "D. A vehicle lost control due to wet road conditions\n"
        "======\n"
        "Answer: A. The collision was caused by a vehicle entering the "
        "intersection against a red signal.\n"
        "=====\n"
        "Reasoning:\n"
        "The video shows a standard intersection with traffic signals. "
        "At 00:00:05, the signal changes giving right-of-way to "
        "cross-traffic. A blue sedan continues through the intersection "
        "from the perpendicular direction despite the red signal, "
        "colliding with a white SUV that had just started moving on the "
        "fresh green. The road surface appears dry and no pedestrians "
        "are visible, ruling out options C and D. No U-turn is "
        "attempted, ruling out B. The root cause is the blue sedan's "
        "red light violation.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Multiple-Choice Question: [Question]\n"
        "A. [Option A]\n"
        "B. [Option B]\n"
        "C. [Option C]\n"
        "D. [Option D]\n"
        "======\n"
        "Answer: [Answer] (should be a single letter choice)\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}\n\n"
        "[Chunk Captions]\n{chunk_captions_str}\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    "normal_mcq": (
        "You are an expert video analyst. You are provided with captions "
        "for a video with a normal scenario.\n\n"
        "Task:\n"
        "1. Design a multiple-choice question that requires perception "
        "and preferably reasoning to answer.\n"
        "2. The question should focus on: identifying what is happening, "
        "who or what is involved, the sequence of events, spatial "
        "relationships, or environmental conditions.\n"
        "3. The question must be unambiguous with exactly one correct "
        "answer. Each wrong option must be clearly incorrect, not "
        "merely less likely. All options should be specific and parallel.\n"
        "4. Provide step-by-step reasoning to derive the answer.\n"
        "5. Treat all captions as a representation of the video itself. "
        'Don\'t mention "Global Caption" or "Dense Caption" \u2014 only '
        "mention the video.\n"
        "6. Ground your output on the provided data. Don't hallucinate.\n\n"
        "Here is an example of the desired content style and depth. "
        "(Note: this is for illustration only.)\n"
        "<example>\n"
        "Multiple-Choice Question: What does the person in the yellow "
        "vest do after picking up the package?\n"
        "A. Places it on a shelf to the left of the frame\n"
        "B. Carries it to a loading cart near the exit door\n"
        "C. Hands it to another worker standing nearby\n"
        "D. Sets it down on the conveyor belt behind them\n"
        "======\n"
        "Answer: B. The worker carries the package to a loading cart "
        "positioned near the exit door on the right side of the frame.\n"
        "=====\n"
        "Reasoning:\n"
        "In the video, the person in the yellow vest picks up a brown "
        "package from a pallet at approximately 00:00:06. They then "
        "walk to the right side of the frame toward the exit door, where "
        "a metal loading cart is parked. They place the package on the "
        "cart at 00:00:10. No shelf is visible on the left, no other "
        "worker is standing nearby to receive the package, and the "
        "conveyor belt is behind them and not interacted with.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Multiple-Choice Question: [Question]\n"
        "A. [Option A]\n"
        "B. [Option B]\n"
        "C. [Option C]\n"
        "D. [Option D]\n"
        "======\n"
        "Answer: [Answer] (should be a single letter choice)\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}"
    ),
    # =========================================================================
    # QA GENERATION \u2014 BINARY
    # =========================================================================
    "anomaly_bcq": (
        "You are an expert video analyst. You are provided with captions "
        "and a description for a video containing an anomaly.\n\n"
        "Task:\n"
        '1. Design two binary questions, one with answer "Yes." and '
        'one with answer "No.". Don\'t make the questions too '
        "complicated. They should be straightforward but still require "
        "observing and reasoning about the video carefully.\n"
        "2. For each question, provide a step-by-step reasoning of how "
        "to derive the answer based on the video. Start from observation "
        "and description of the video and the anomalous event, then "
        "reason/analyze the question.\n"
        "3. Treat the description as a representation of the video "
        "itself. Generate the Question, Answer, and Reasoning as if you "
        "are looking at the video directly. Don't mention the description "
        "in the Question, Answer, or Reasoning. Only mention the video.\n"
        "4. Ground your output on the provided data. Don't hallucinate.\n\n"
        "Here is an example of the desired content style and depth. "
        "(Note: this is for illustration only \u2014 your output must be "
        "based on the actual content of the video provided, not this "
        "example.)\n"
        "<example>\n"
        "Question: Is the person in the dark jacket involved in the "
        "incident?\n"
        "======\n"
        "Answer: Yes. In the video, the person in the dark jacket is "
        "directly involved \u2014 they are the one who initiates the unsafe "
        "action at 00:00:08, reaching across the moving conveyor belt "
        "without stopping it first.\n"
        "=====\n"
        "Reasoning:\n"
        "The video shows a warehouse packing station with two workers. "
        "At 00:00:05, both are standing near the conveyor belt. At "
        "00:00:08, the person in the dark jacket reaches across the "
        "moving belt to grab a box from the other side, placing their "
        "arm in the path of the belt's motion. The other worker in the "
        "yellow vest steps back. This confirms the person in the dark "
        "jacket is directly involved in the unsafe action.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "1. Question: [Question]\n"
        "======\n"
        "Answer: Yes. [Additional explanation in one sentence]\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n"
        "=====\n"
        "2. Question: [Question]\n"
        "======\n"
        "Answer: No. [Additional explanation in one sentence]\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}\n\n"
        "[Chunk Captions]\n{chunk_captions_str}\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    "normal_bcq": (
        "You are an expert video analyst. You are provided with captions "
        "for a video with a normal scenario.\n\n"
        "Task:\n"
        '1. Design two binary questions, one with answer "Yes." and '
        'one with answer "No.". Don\'t make the questions too '
        "complicated. They should be straightforward but still require "
        "observing and reasoning about the video carefully. Focus on "
        "observable events, actor behaviors, spatial relationships, "
        "or environmental conditions.\n"
        "2. For each question, provide a step-by-step reasoning of "
        "how to derive the answer based on the video. Start from "
        "observation and description, then reason/analyze.\n"
        "3. Treat the description as a representation of the video "
        "itself. Don't mention the description. Only mention the video.\n"
        "4. Ground your output on the provided data. Don't hallucinate.\n\n"
        "Here is an example of the desired content style and depth. "
        "(Note: this is for illustration only.)\n"
        "<example>\n"
        "Question: Does the worker finish loading all the boxes onto "
        "the cart before the end of the video?\n"
        "======\n"
        "Answer: Yes. After the traffic signal transitions to green, "
        "the vehicles that had been queued begin moving and clear the "
        "intersection within approximately 10 seconds.\n"
        "=====\n"
        "Reasoning:\n"
        "The video shows the worker loading boxes from a pallet onto "
        "a cart starting at 00:00:03. The pallet initially has "
        "approximately six boxes. The worker transfers them one at a "
        "time. By 00:00:20, the last box is placed on the cart and "
        "the pallet is empty. The worker then pushes the cart toward "
        "the exit, confirming all boxes were loaded before the video "
        "ends.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "1. Question: [Question]\n"
        "======\n"
        "Answer: Yes. [Additional explanation in one sentence]\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n"
        "=====\n"
        "2. Question: [Question]\n"
        "======\n"
        "Answer: No. [Additional explanation in one sentence]\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}"
    ),
    # =========================================================================
    # QA GENERATION \u2014 OPEN-ENDED
    # =========================================================================
    "anomaly_open_qa": (
        "You are an expert video analyst. You are provided with captions "
        "and a description for a video containing an anomaly.\n\n"
        "Task:\n"
        "1. Design an open-ended question about the anomaly that "
        "requires perception and reasoning to answer.\n"
        "2. The question should ask about the root cause, consequence, "
        "sequence of events, or what should have been done differently.\n"
        "3. Provide step-by-step reasoning to derive the answer. The "
        "reasoning should proceed from observations (what is visible) "
        "through causal inference to the conclusion.\n"
        "4. Treat all captions as a representation of the video itself. "
        'Don\'t mention "Global Caption", "Dense Caption", or '
        '"Chunk Captions" \u2014 only mention the video.\n'
        "5. Ground your output on the provided data. Don't hallucinate.\n\n"
        "Here is an example of the desired content style and depth. "
        "(Note: this is for illustration only \u2014 your output must be "
        "based on the actual content of the video provided, not this "
        "example.)\n"
        "<example>\n"
        "Open-ended Question: What is the root cause of the incident "
        "in the video?\n"
        "======\n"
        "Answer: The root cause of the incident is the person in the "
        "dark jacket reaching across an active conveyor belt without "
        "first stopping or disabling it. This unsafe action at 00:00:08 "
        "placed their arm directly in the path of moving machinery, "
        "creating an immediate risk of entanglement or injury. The "
        "proper procedure would have been to press the emergency stop "
        "or use the belt's off switch before reaching across.\n"
        "=====\n"
        "Reasoning:\n"
        "The video shows a packing station where two workers are "
        "operating near a conveyor belt. Before 00:00:08, both workers "
        "are positioned safely on the same side of the belt, performing "
        "routine packing tasks. The belt is running continuously, "
        "transporting packages from right to left.\n\n"
        "At 00:00:08, the person in the dark jacket leans across the "
        "moving belt to retrieve a box that has shifted to the far "
        "side. Their forearm passes directly over the belt surface "
        "while it is still in motion. The second worker in the yellow "
        "vest visibly steps back, suggesting they recognized the danger.\n\n"
        "The root cause is the failure to stop the conveyor before "
        "reaching across it. Standard safety procedure requires "
        "stopping moving machinery before reaching into or across its "
        "path of motion. The urgency to retrieve the box led to a "
        "shortcut that bypassed this safety protocol.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Open-ended Question: [Question]\n"
        "======\n"
        "Answer: [Answer] (open-ended, should be a paragraph)\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}\n\n"
        "[Chunk Captions]\n{chunk_captions_str}\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    "normal_open_qa": (
        "You are an expert video analyst. You are provided with captions "
        "for a video with a normal scenario.\n\n"
        "Task:\n"
        "1. Design an open-ended question that requires perception and "
        "preferably reasoning to answer.\n"
        "2. The question should ask about what is happening, why events "
        "unfold as they do, how actors interact, or what the observable "
        "patterns reveal about the scene.\n"
        "3. Provide step-by-step reasoning to derive the answer.\n"
        "4. Treat all captions as a representation of the video itself. "
        'Don\'t mention "Global Caption" or "Dense Caption" \u2014 only '
        "mention the video.\n"
        "5. Ground your output on the provided data. Don't hallucinate.\n\n"
        "Here is an example of the desired content style and depth. "
        "(Note: this is for illustration only.)\n"
        "<example>\n"
        "Open-ended Question: What is the workflow being performed by "
        "the workers in the video, and how do they coordinate?\n"
        "======\n"
        "Answer: The two workers are performing a box-loading operation "
        "where one worker retrieves boxes from a pallet and places them "
        "on a shared cart, while the other arranges and secures the "
        "boxes on the cart for transport. They coordinate through "
        "spatial positioning \u2014 the first worker handles the heavy "
        "lifting from the pallet side while the second organizes from "
        "the cart side, maintaining a smooth continuous flow without "
        "verbal cues visible in the video.\n"
        "=====\n"
        "Reasoning:\n"
        "The video shows two workers at a warehouse loading station. "
        "From 00:00:02, the first worker in a blue shirt begins "
        "picking up boxes from a pallet and placing them on a metal "
        "cart. The second worker in a yellow vest positions boxes on "
        "the cart, stacking and arranging them. They alternate access "
        "to the cart without colliding or pausing, suggesting a "
        "practiced routine. By 00:00:18, approximately eight boxes "
        "have been transferred. The division of labor \u2014 one lifting, "
        "one organizing \u2014 allows continuous movement without either "
        "worker waiting for the other.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Open-ended Question: [Question]\n"
        "======\n"
        "Answer: [Answer] (open-ended, should be a paragraph)\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Global Caption]\n{global_caption}\n\n"
        "[Dense Caption]\n{dense_caption}"
    ),
    # =========================================================================
    # QA GENERATION — SCENE DESCRIPTION (mode-independent)
    # =========================================================================
    "scene_description": (
        "You are an expert video analyst. You are provided with a "
        "detailed description for a video. Your task is to produce a "
        "**scene description caption** that captures the static, spatial "
        "layout of the scene — not the events that unfold over time.\n\n"
        "Task:\n"
        "1. Write a **question** — a natural-language question whose "
        "answer is the scene description caption. The question should "
        "ask about the physical setting, layout, or environmental "
        'context of the video (e.g., "What does the scene look like '
        'in this video?" or "Describe the layout and surroundings '
        'visible in the video.").\n'
        "2. Write an **answer** — a concise yet thorough scene "
        "description covering:\n"
        "   - The camera perspective (overhead, eye-level, fixed CCTV, "
        "dashboard, etc.).\n"
        "   - Weather, lighting, and approximate time of day.\n"
        "   - Physical layout: the arrangement of spaces, paths, lanes, "
        "corridors, or areas visible in the scene.\n"
        "   - Infrastructure: signs, signals, lights, barriers, "
        "doorways, equipment, or other fixed elements.\n"
        "   - Stationary objects and environment: buildings, vegetation, "
        "parked vehicles, furniture, text overlays.\n"
        "   - People/objects present and their attributes (color, type, "
        "size) when discernible.\n"
        "   Do NOT describe events, movements, or actions — those "
        "belong in the event summary.\n"
        "3. Write a **reasoning** — a coherent paragraph explaining how "
        "observations from the video lead to each element of the "
        "answer. Proceed from what is directly visible to the "
        "inferences drawn. Do not use bullet points or numbered lists.\n"
        "4. Treat the description as a representation of the video "
        "itself. Generate the Question, Answer, and Reasoning as if "
        "you are looking at the video directly. Do not mention the "
        "description in the output.\n"
        "5. Ground your output on the provided data. Do not hallucinate "
        "or fabricate details.\n\n"
        "Here are examples of the desired answer style and depth. "
        "(Note: these are for illustration only — your output must be "
        "based on the actual content of the video provided, not these "
        "examples.)\n"
        "<example>\n"
        "Answer: The video is captured from an overhead camera during "
        "the daytime, showing a four-lane roadway. Lanes 1 and 2 flow "
        "from top to bottom of the frame, while lanes 3 and 4 flow "
        "from bottom to top. A median divider separates the opposing "
        "directions. Street lights line both sides of the road, and a "
        "pedestrian crosswalk is visible at the intersection.\n"
        "</example>\n"
        "<example>\n"
        "Answer: The scene shows a wide warehouse interior with high "
        "ceilings and fluorescent lighting. Metal shelving units line "
        "both walls, stacked with boxes and pallets. A concrete floor "
        "extends from the foreground to a loading dock area visible in "
        "the background. A yellow forklift is parked to the left, and "
        "safety signage is mounted near the entrance.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Question about the scene layout]\n"
        "=====\n"
        "Answer: [Scene description caption]\n"
        "=====\n"
        "Reasoning: [Coherent paragraph deriving each answer element "
        "from video observations]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    # =========================================================================
    # QA GENERATION — EVENT SUMMARY (mode-independent)
    # =========================================================================
    "event_summary": (
        "You are an expert video analyst. You are provided with a "
        "detailed description for a video. Your task is to produce an "
        "**event summary caption** that describes the key events and "
        "actions in the video — not the static scene layout.\n\n"
        "Task:\n"
        "1. Write a **question** — a natural-language question whose "
        "answer is the event summary caption. The question should ask "
        'about what happens in the video (e.g., "What are the key '
        'events in this video?" or "Summarize the events and any '
        'anomalies observed in the video.").\n'
        "2. Write an **answer** — a concise yet thorough event summary "
        "covering:\n"
        "   - A brief, high-level summary of all key events.\n"
        "   - For normal activity: describe the activity flow and any "
        "notable behaviors or interactions.\n"
        "   - For anomalous activity: briefly describe normal activity, "
        "then describe the anomaly in detail, including the actors "
        "involved (with distinguishing attributes like color, type), "
        "the sequence of events, and the physical aftermath.\n"
        "   - **Root cause**: For any anomaly, explicitly state the "
        "root cause of the incident.\n"
        "   - Use timestamps (MM:SS) and spatial references where "
        "possible.\n"
        "3. Write a **reasoning** — a coherent paragraph explaining the "
        "chain of observations and inferences that support the answer. "
        "Start from what is visible, trace the sequence of events, and "
        "connect them to the stated outcome or root cause. Do not use "
        "bullet points or numbered lists.\n"
        "4. Treat the description as a representation of the video "
        "itself. Generate the Question, Answer, and Reasoning as if "
        "you are looking at the video directly. Do not mention the "
        "description in the output.\n"
        "5. Ground your output on the provided data. Do not hallucinate "
        "or fabricate details.\n\n"
        "Here are examples of the desired answer style and depth. "
        "(Note: these are for illustration only.)\n"
        "<example>\n"
        "Answer: The video shows two workers performing a coordinated "
        "loading operation at a warehouse dock. Worker A retrieves "
        "boxes from a pallet and transfers them to a shared cart, "
        "while Worker B arranges and secures the boxes for transport. "
        "By the end of the clip, approximately eight boxes have been "
        "loaded and the cart is pushed toward the exit.\n"
        "</example>\n"
        "<example>\n"
        "Answer: A blue sedan enters the frame and collides with a "
        "black SUV ahead of it. After the collision, the blue sedan "
        "changes lanes without signaling and becomes stalled, while "
        "the black SUV moves to the shoulder. The root cause is the "
        "blue sedan's failure to maintain a safe following distance.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Question about the events in the video]\n"
        "=====\n"
        "Answer: [Event summary caption]\n"
        "=====\n"
        "Reasoning: [Coherent paragraph tracing the sequence of events "
        "from video observations]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    # =========================================================================
    # QA GENERATION — TEMPORAL EVENT DESCRIPTION
    # =========================================================================
    "anomaly_temporal_event_desc": (
        "You are an expert video analyst. You are provided with a "
        "detailed description for a video containing an anomaly.\n\n"
        "Task:\n"
        "1. Identify a single anomalous event (e.g., a collision, a "
        "violation, a near-miss, an equipment failure) and select "
        "[t1, t2] as the tight temporal window covering just that one "
        "event.\n\n"
        "2. Generate a question asking what happened in the video "
        "between [t1] and [t2]. The question must contain ONLY the "
        "timestamps and a neutral phrasing — no actors, actions, "
        "events, or outcomes.\n\n"
        "3. Provide an Answer as a single coherent paragraph describing "
        "what occurred in that window, including the inferred cause of "
        "the anomaly woven naturally into the description.\n\n"
        "4. Provide a Reasoning trace in 2-3 coherent paragraphs "
        "explaining your observations in addition to what changed and "
        "why during the window itself. Where applicable, include "
        "pre-event context before t1 (the normal baseline state that "
        "makes the anomaly identifiable) and post-event context after "
        "t2 (the resulting state or consequence).\n\n"
        "Constraints:\n"
        "- STRICT ADHERENCE TO TIMESTAMPS: Use only timestamps "
        "supported by the provided description. Do not hallucinate "
        "times.\n"
        "- The Question must contain ONLY the timestamps and a neutral "
        "phrasing — no actors, events, outcomes, or causes.\n"
        "- The Answer must be a single coherent paragraph. Do not use "
        "bullet points or numbered lists.\n"
        "- The Reasoning must be coherent paragraphs. Do not use "
        "bullet points or numbered lists.\n"
        "- Treat the description as a representation of the video "
        "itself. Generate the Question, Answer, and Reasoning as if "
        "you are looking at the video directly. Do not mention the "
        "description in the output.\n\n"
        "Here is an example of the desired output:\n"
        "<example>\n"
        "Question: What happened in the video between 00:00:02 and "
        "00:00:06?\n"
        "======\n"
        "Answer: A person reaches across an active conveyor belt "
        "without first stopping it, placing their arm in the path of "
        "moving machinery. A nearby worker steps back in alarm. The "
        "root cause is the failure to follow the stop-before-reaching "
        "safety protocol.\n"
        "=====\n"
        "Reasoning:\n"
        "Before 00:00:02, both workers are positioned safely on the "
        "same side of the belt, performing routine tasks. The belt is "
        "running continuously. This baseline of orderly, safe behavior "
        "is what makes the subsequent deviation identifiable.\n\n"
        "At 00:00:02, one worker leans across the moving belt to "
        "retrieve an item on the far side. Their forearm passes "
        "directly over the belt surface while it is still in motion. "
        "The second worker visibly steps back.\n\n"
        "After 00:00:06, the belt is still running and the worker has "
        "retracted their arm. The root cause is the urgency to "
        "retrieve the item, which led to bypassing the standard "
        "stop-first protocol.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Neutral question with only timestamps]\n"
        "======\n"
        "Answer: [Single paragraph]\n"
        "=====\n"
        "Reasoning: [2-3 coherent paragraphs]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    "normal_temporal_event_desc": (
        "You are an expert video analyst. You are provided with a "
        "detailed description for a normal video.\n\n"
        "Task:\n"
        "1. Identify a single, self-contained event (e.g., a person "
        "completing a task, a vehicle maneuver, an interaction between "
        "actors) and select [t1, t2] as the tight temporal window "
        "covering just that one event.\n\n"
        "2. Generate a question asking what happened in the video "
        "between [t1] and [t2]. The question must contain ONLY the "
        "timestamps and a neutral phrasing — no actors, actions, "
        "events, or outcomes.\n\n"
        "3. Provide an Answer as a single coherent paragraph describing "
        "what occurred in that window and why the events unfolded as "
        "they did.\n\n"
        "4. Provide a Reasoning trace in 2-3 coherent paragraphs "
        "explaining your observations in addition to what changed and "
        "why during the window itself. Where applicable, include "
        "pre-event context before t1 (what led to the event) and "
        "post-event context after t2 (the resulting state).\n\n"
        "Constraints:\n"
        "- STRICT ADHERENCE TO TIMESTAMPS: Use only timestamps "
        "supported by the provided description. Do not hallucinate "
        "times.\n"
        "- The Question must contain ONLY the timestamps and a neutral "
        "phrasing — no actors, events, outcomes, or causes.\n"
        "- The Answer must be a single coherent paragraph. Do not use "
        "bullet points or numbered lists.\n"
        "- The Reasoning must be coherent paragraphs. Do not use "
        "bullet points or numbered lists.\n"
        "- Treat the description as a representation of the video "
        "itself. Generate the Question, Answer, and Reasoning as if "
        "you are looking at the video directly. Do not mention the "
        "description in the output.\n\n"
        "Here is an example of the desired output:\n"
        "<example>\n"
        "Question: What happened in the video between 00:00:08 and "
        "00:00:12?\n"
        "======\n"
        "Answer: A worker picks up a box from the pallet and carries "
        "it to the loading cart near the exit, placing it alongside "
        "the previously loaded items. The transfer is smooth and "
        "follows the established loading routine.\n"
        "=====\n"
        "Reasoning:\n"
        "Before 00:00:08, the worker has been steadily transferring "
        "boxes one at a time from the pallet to the cart. The pallet "
        "still has several boxes remaining.\n\n"
        "At 00:00:08, the worker bends down and lifts the next box, "
        "then walks to the cart and sets it down. By 00:00:12, the "
        "box is in place and the worker turns back toward the pallet "
        "for the next item.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Neutral question with only timestamps]\n"
        "======\n"
        "Answer: [Single paragraph]\n"
        "=====\n"
        "Reasoning: [2-3 coherent paragraphs]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    # =========================================================================
    # QA GENERATION — CAUSAL LINKAGE
    # =========================================================================
    "anomaly_causal_linkage": (
        "You are an expert video analyst. You are provided with a "
        "detailed description for a video containing an anomaly.\n\n"
        "Task:\n"
        "1. Identify two distinct moments:\n"
        "   - [Timestamp A] (Reference Point): The triggering action, "
        "violation, or initial condition.\n"
        "   - [Timestamp B] (Focus Point): The subsequent outcome or "
        "resulting consequence.\n"
        '2. Generate a "Blind" Open-ended Question about the '
        "relationship between the two moments using ONLY their "
        "timestamps.\n"
        '   - FORMAT example: "Explain the relationship between the '
        'event at [Timestamp A] and the situation at [Timestamp B]."\n'
        "   - CONSTRAINT: Do not mention any specific actors, actions, "
        "or outcomes in the question.\n"
        "   - Design questions that require perception and reasoning "
        "to answer.\n"
        "3. Provide a Detailed Answer in a single paragraph:\n"
        "   - Begin by explicitly identifying the specific event at "
        "[Timestamp A] and the specific situation at [Timestamp B].\n"
        "   - Follow with a narrative explanation of the logical, "
        "physical, or causal connection.\n"
        "4. Provide a Reasoning Trace in 2\u20133 coherent paragraphs:\n"
        "   - Start from observation: identify the events at A and B. "
        "Describe the baseline state before [Timestamp A].\n"
        '   - Trace the "Logical Bridge" between A and B. Highlight '
        "the key events needed to answer the question.\n"
        "   - Reason through the causal chain and state the "
        "conclusion.\n\n"
        "Constraints:\n"
        '- The question MUST be "blind" (refer only to timestamps).\n'
        "- The Answer must be a single, comprehensive narrative "
        "paragraph.\n"
        "- The Reasoning must be coherent paragraphs (no bullet points "
        "or lists).\n"
        "- STRICT ADHERENCE TO TIMESTAMPS: Use the exact timestamps "
        "from the provided description.\n"
        "- Treat the description as a representation of the video "
        "itself. Generate the Question, Answer, and Reasoning as if "
        "you are looking at the video directly. Do not mention the "
        "description in the output.\n\n"
        "Here is an example of the desired content style and depth:\n"
        "<example>\n"
        "Question: Explain the relationship between the event at "
        "00:00:01 and the situation at 00:00:05.\n"
        "======\n"
        "Answer: At 00:00:01, a person bypasses the safety barrier "
        "and enters the restricted zone while machinery is active, "
        "and at 00:00:05, the emergency stop has been triggered and "
        "all equipment is halted. The relationship is a direct causal "
        "chain where the unauthorized entry triggered an automatic "
        "safety shutdown, resulting in the full stoppage observed at "
        "00:00:05.\n"
        "=====\n"
        "Reasoning:\n"
        "The video shows a normal operational state before 00:00:01, "
        "with machinery running and workers positioned outside the "
        "barrier. At 00:00:01, a person crosses the barrier into the "
        "active zone.\n\n"
        "Between these timestamps, the proximity sensor detects the "
        "intrusion and triggers the emergency protocol. The machinery "
        "begins its shutdown sequence.\n\n"
        "By 00:00:05, all equipment has stopped and warning lights "
        "are active. The situation at 00:00:05 is the direct result "
        "of the unauthorized entry at 00:00:01.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Question]\n"
        "======\n"
        "Answer: [Answer] (open-ended, should be a paragraph)\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    "normal_causal_linkage": (
        "You are an expert video analyst. You are provided with a "
        "detailed description for a normal video.\n\n"
        "Task:\n"
        "1. Identify two distinct moments:\n"
        "   - [Timestamp A] (Reference Point): An initial action or "
        "condition (e.g., a signal change, beginning of a maneuver, "
        "start of a task).\n"
        "   - [Timestamp B] (Focus Point): The subsequent outcome "
        "(e.g., task completed, maneuver finished, flow resumed).\n"
        '2. Generate a "Blind" Open-ended Question about the '
        "relationship between the two moments using ONLY their "
        "timestamps.\n"
        '   - FORMAT example: "Explain the relationship between the '
        'event at [Timestamp A] and the situation at [Timestamp B]."\n'
        "   - CONSTRAINT: Do not mention any specific actors, actions, "
        "or outcomes in the question.\n"
        "   - The relationship can be causal (cause/effect), sequential "
        "(action/completion), or regulatory (signal/response).\n"
        "3. Provide a Detailed Answer in a single paragraph:\n"
        "   - Begin by explicitly identifying the specific event at "
        "[Timestamp A] and the specific situation at [Timestamp B].\n"
        "   - Follow with a narrative explanation of the logical "
        "connection.\n"
        "4. Provide a Reasoning Trace in 2\u20133 coherent paragraphs:\n"
        "   - Start from observation: identify the events at A and B. "
        "Describe the baseline state before [Timestamp A].\n"
        '   - Trace the "Logical Bridge" between A and B.\n'
        "   - Reason through the chain and state the conclusion.\n\n"
        "Constraints:\n"
        '- The question MUST be "blind" (refer only to timestamps).\n'
        "- The Answer must be a single, comprehensive narrative "
        "paragraph.\n"
        "- The Reasoning must be coherent paragraphs (no bullet points "
        "or lists).\n"
        "- STRICT ADHERENCE TO TIMESTAMPS: Use the exact timestamps "
        "from the provided description.\n"
        "- Treat the description as a representation of the video "
        "itself. Generate the Question, Answer, and Reasoning as if "
        "you are looking at the video directly. Do not mention the "
        "description in the output.\n\n"
        "Here is an example of the desired content style and depth:\n"
        "<example>\n"
        "Question: Explain the relationship between the event at "
        "00:00:08 and the situation at 00:00:12.\n"
        "======\n"
        "Answer: At 00:00:08, a worker begins transferring a box from "
        "the pallet to the loading cart, and at 00:00:12 the same "
        "box has been placed on the cart and the worker is returning "
        "for the next item. The relationship is sequential: the event "
        "at 00:00:08 is the start of a single transfer action, and "
        "the situation at 00:00:12 is its natural completion.\n"
        "=====\n"
        "Reasoning:\n"
        "Before 00:00:08, the worker has been steadily loading boxes. "
        "At 00:00:08, they pick up the next box and begin walking "
        "toward the cart.\n\n"
        "The bridge between these moments is the physical transfer: "
        "the worker carries the box across the workspace and sets it "
        "on the cart.\n\n"
        "By 00:00:12, the box is in place and the worker has turned "
        "back. The situation at 00:00:12 is the direct completion of "
        "the action initiated at 00:00:08.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Question]\n"
        "======\n"
        "Answer: [Answer] (open-ended, should be a paragraph)\n"
        "=====\n"
        "Reasoning: [Provide the analysis as coherent paragraphs. "
        "Do not use bullet points or numbered lists.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    # =========================================================================
    # QA GENERATION — TEMPORAL LOCALIZATION
    # =========================================================================
    "anomaly_temporal_localization": (
        "You are an expert video analyst specializing in temporal "
        "localization. You are provided with a detailed description "
        "for a video containing an anomaly.\n\n"
        "Task:\n"
        "1. Identify a significant event or anomaly that requires "
        "logical reasoning to localize.\n"
        "2. Generate a Temporal Localization Question in the format: "
        '"When does [Event X] occur in the video?"\n'
        "3. Provide the Answer with exact start and end timestamps.\n"
        "4. Provide a detailed Reasoning paragraph following a "
        "three-phase logical trace:\n"
        "   - Describe the state of the video immediately before the "
        "start timestamp. Identify the normal patterns that were "
        "being followed to establish why the event had NOT yet begun.\n"
        "   - Pinpoint the exact visual state-change at the start "
        "timestamp. Explain the root cause that initiated the "
        "anomaly.\n"
        "   - Justify the end timestamp by describing the transition "
        "into a new, stable, or static state.\n\n"
        "Constraints:\n"
        "- The reasoning must follow the structure: Baseline \u2192 "
        "Trigger \u2192 Resolution.\n"
        "- STRICT ADHERENCE TO TIMESTAMPS: Do not hallucinate times. "
        "Use only timestamps from the provided description.\n"
        "- The Reasoning section must be a coherent, dense paragraph. "
        "Do not use bullet points or numbered lists.\n"
        "- Treat the description as a representation of the video "
        "itself. Do not mention the description; describe the video "
        "directly.\n\n"
        "Here is an example of the desired content style and depth:\n"
        "<example>\n"
        "Question: When does the collision between the forklift and "
        "the shelving unit occur?\n"
        "======\n"
        "Answer: Start_Time: 00:00:03, End_Time: 00:00:07\n"
        "=====\n"
        "Reasoning:\n"
        "Prior to 00:00:03, the forklift is traveling along the aisle "
        "at moderate speed with its forks raised. Workers are "
        "positioned at a safe distance. At 00:00:03, the forklift "
        "operator turns sharply into a cross-aisle and the raised "
        "forks catch the edge of a shelving unit, initiating the "
        "impact. Between 00:00:03 and 00:00:07, the shelving unit "
        "tilts and several boxes fall to the floor. By 00:00:07, the "
        "forklift has stopped, the shelving unit has settled at an "
        "angle, and the scene transitions to a static state with "
        "debris on the ground.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Question]\n"
        "======\n"
        "Answer: Start_Time: [MM:SS], End_Time: [MM:SS]\n"
        "=====\n"
        "Reasoning: [Provide the analysis as a coherent paragraph. "
        "Describe the baseline, the trigger, and the resolution.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
    "normal_temporal_localization": (
        "You are an expert video analyst specializing in temporal "
        "localization. You are provided with a detailed description "
        "for a normal video.\n\n"
        "Task:\n"
        "1. Identify a significant event that requires logical "
        "reasoning to localize. Focus on regular events such as:\n"
        "   - A person completing a task or action\n"
        "   - A state change in the environment (signal, door, "
        "equipment)\n"
        "   - An interaction between actors\n"
        "   - A transition in activity flow\n\n"
        "2. Generate a Temporal Localization Question in the format: "
        '"When does [Event X] occur in the video?"\n'
        "3. Provide the Answer with exact start and end timestamps.\n"
        "4. Provide a detailed Reasoning paragraph following a "
        "three-phase logical trace:\n"
        "   - Describe the state immediately before the start "
        "timestamp.\n"
        "   - Pinpoint the exact visual state-change at the start "
        "timestamp.\n"
        "   - Justify the end timestamp by describing the transition "
        "into a new, stable state.\n\n"
        "Constraints:\n"
        "- The reasoning must follow the structure: Before-State \u2192 "
        "Action/Transition \u2192 After-State.\n"
        "- STRICT ADHERENCE TO TIMESTAMPS: Do not hallucinate times.\n"
        "- The Reasoning section must be a coherent, dense paragraph. "
        "Do not use bullet points or numbered lists.\n"
        "- Treat the description as a representation of the video "
        "itself. Do not mention the description; describe the video "
        "directly.\n\n"
        "Here is an example of the desired content style and depth:\n"
        "<example>\n"
        "Question: When does the worker finish loading all the boxes "
        "onto the cart?\n"
        "======\n"
        "Answer: Start_Time: 00:00:15, End_Time: 00:00:20\n"
        "=====\n"
        "Reasoning:\n"
        "Prior to 00:00:15, the worker has been transferring boxes one "
        "at a time from the pallet to the cart. The pallet has two "
        "remaining boxes. At 00:00:15, the worker picks up the "
        "second-to-last box and places it on the cart, then "
        "immediately reaches for the final box. By 00:00:20, the last "
        "box is on the cart, the pallet is empty, and the worker steps "
        "back to push the cart toward the exit, marking the completion "
        "of the loading task.\n"
        "</example>\n\n"
        "Format:\n"
        "=====\n"
        "Question: [Question]\n"
        "======\n"
        "Answer: Start_Time: [MM:SS], End_Time: [MM:SS]\n"
        "=====\n"
        "Reasoning: [Provide the analysis as a coherent paragraph. "
        "Describe the before-state, the action, and the after-state.]\n\n"
        "Input Data:\n"
        "Video Length: {video_length}s\n\n"
        "[Detailed Video Description]\n{step_2_output}"
    ),
}


def get_prompt(key, **kwargs):
    """Retrieve and optionally format a prompt template by key.

    Args:
        key (str): Template name (e.g. ``"anomaly_global_caption"``).
        **kwargs: Substitution values passed to ``str.format()``.
            When empty, the raw template string is returned.

    Returns:
        str: The prompt text, with placeholders filled if *kwargs*
            were provided.

    Raises:
        ValueError: If *key* is not found in ``PROMPT_TEMPLATES``.
    """
    template = PROMPT_TEMPLATES.get(key)
    if template is None:
        raise ValueError(f"No prompt template found for key: {key}")
    if kwargs:
        return template.format(**kwargs)
    return template
